'use client';

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-warm-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-neutral-900 mb-8">Terms of Service</h1>
        <p className="text-sm text-neutral-500 mb-8">Last Updated: January 2025</p>
        
        <div className="prose prose-neutral max-w-none space-y-8">
          
          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Affiliate Disclosure</h2>
            <p className="text-neutral-600 mb-4">
              This website participates in affiliate marketing programs. We may earn commissions when 
              you click links and make purchases through our affiliate partners, including but not 
              limited to Amazon Associates.
            </p>
            <p className="text-neutral-600 font-medium">
              As an Amazon Associate, we earn from qualifying purchases.
            </p>
            <p className="text-neutral-600 mt-4">
              Product recommendations, trend scores, and rankings are generated by our AI-powered systems 
              analyzing social media trends, product data, and user engagement. Affiliate commission rates 
              do not influence our trend scores or recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">AI-Powered Recommendations</h2>
            <p className="text-neutral-600 mb-4">Our platform uses artificial intelligence to:</p>
            <ul className="list-disc pl-6 text-neutral-600 space-y-2">
              <li>Analyze publicly available social media trends</li>
              <li>Generate product trend scores and recommendations</li>
              <li>Match your described problems with relevant product types</li>
            </ul>
            <p className="text-neutral-600 mt-4">
              AI-generated recommendations are provided for informational purposes only. We do not guarantee 
              the accuracy, completeness, or suitability of any recommendation. Always verify product 
              information with the retailer before purchasing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Third-Party Data & API Compliance</h2>
            <p className="text-neutral-600 mb-4">
              We aggregate trend data from multiple social platforms to provide product recommendations. 
              Our service complies with all third-party API terms of service:
            </p>
            <ul className="list-disc pl-6 text-neutral-600 space-y-2">
              <li><strong>YouTube</strong> - Content usage follows YouTube Data API policies</li>
              <li><strong>Reddit</strong> - Data accessed through official OAuth flows</li>
              <li><strong>Google Trends</strong> - Used for trend analysis and search volume insights</li>
              <li><strong>Amazon</strong> - Product data and pricing information</li>
            </ul>
            <p className="text-neutral-600 mt-4">
              All third-party content belongs to the respective platforms and their users. We do not 
              claim ownership of any third-party content displayed on our site.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Disclaimer of Warranties</h2>
            <p className="text-neutral-600">
              THE PLATFORM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, 
              EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. 
              Product recommendations are generated algorithmically and may not suit your specific needs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Limitation of Liability</h2>
            <p className="text-neutral-600">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE PLATFORM. Our total 
              liability for any claim shall not exceed the amount you paid us (if any) in the twelve months 
              preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Data Accuracy Disclaimer</h2>
            <p className="text-neutral-600 mb-4">
              While we strive to provide accurate trend data and product information, we cannot guarantee 
              the accuracy of information from third-party sources. Product prices, availability, and 
              details may change without notice and should be verified directly with retailers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Acceptable Use Policy</h2>
            <p className="text-neutral-600 mb-4">Users agree to use our service responsibly and not to:</p>
            <ul className="list-disc pl-6 text-neutral-600 space-y-2">
              <li>Attempt to reverse engineer our algorithms or trend analysis systems</li>
              <li>Scrape, bulk download, or systematically access our data</li>
              <li>Use our service for illegal, harmful, or fraudulent purposes</li>
              <li>Violate any applicable laws, regulations, or third-party rights</li>
              <li>Interfere with the proper functioning of our service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Changes to Terms</h2>
            <p className="text-neutral-600 mb-4">
              We may update these Terms periodically. Continued use of our service after changes 
              constitutes acceptance of the updated Terms. We will notify users of material changes 
              through our website or email.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Governing Law</h2>
            <p className="text-neutral-600">
              These Terms are governed by the laws of the State of Illinois without regard to conflict of 
              law principles. Any disputes shall be resolved in the courts of Cook County, Illinois.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-neutral-800 mb-4">Contact Us</h2>
            <p className="text-neutral-600">
              Questions about these Terms should be directed to:<br />
              Prox LLC<br />
              680 N Lake Shore Dr.<br />
              Chicago, IL 60611<br />
              info@proxdesign.com
            </p>
          </section>

        </div>
        
        <div className="mt-12 pt-8 border-t border-neutral-200">
          <a href="/" className="text-oak-600 hover:text-oak-700 font-medium">← Back to Home</a>
        </div>
      </div>
    </main>
  );
}