'use client';

export default function HowItWorks() {
  return (
    <main className="min-h-screen bg-warm-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-neutral-900 mb-4">How It Works</h1>
        <p className="text-lg text-neutral-600 mb-12">
          AI-powered product discovery based on real social media trends
        </p>
        
        {/* Step 1 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              1
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">Describe Your Problem</h2>
              <p className="text-neutral-600">
                Tell us what you're struggling with. "My kitchen counter is always cluttered" or 
                "I need a better home office setup." Our AI understands natural language and 
                identifies what you actually need.
              </p>
            </div>
          </div>
        </div>

        {/* Step 2 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              2
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">We Analyze Social Trends</h2>
              <p className="text-neutral-600">
                Our system monitors what real people are saying on YouTube, Reddit, and Pinterest. 
                We identify which products are genuinely helping people solve problems like yours—not 
                just what's being advertised.
              </p>
            </div>
          </div>
        </div>

        {/* Step 3 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              3
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">Get Trending Product Types</h2>
              <p className="text-neutral-600">
                See products that are actually trending right now, with transparent trend scores 
                showing why they're popular. We show you budget, mid-range, and premium options 
                so you can choose what fits your needs.
              </p>
            </div>
          </div>
        </div>

        {/* Transparency Section */}
        <div className="bg-sage-50 rounded-2xl border border-sage-200 p-8 mt-12">
          <h2 className="text-xl font-bold text-neutral-900 mb-4">🤖 AI Transparency</h2>
          <p className="text-neutral-600 mb-4">
            Our recommendations are generated by artificial intelligence analyzing public social media 
            data and product information. Trend scores reflect genuine social engagement—not paid placements.
          </p>
          <p className="text-neutral-600">
            <strong>Affiliate Disclosure:</strong> We earn commissions from purchases made through our links. 
            This doesn't cost you extra and doesn't influence our recommendations—we show trending products 
            regardless of commission rates.
          </p>
        </div>
        
        <div className="mt-12 pt-8 border-t border-neutral-200 flex justify-between items-center">
          <a href="/" className="text-oak-600 hover:text-oak-700 font-medium">← Back to Home</a>
          <a href="/" className="bg-oak-600 hover:bg-oak-700 text-white px-6 py-3 rounded-lg font-medium transition-colors">
            Try It Now
          </a>
        </div>
      </div>
    </main>
  );
}