'use client';

export default function HowItWorks() {
  return (
    <main className="min-h-screen bg-warm-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-neutral-900 mb-4">How It Works</h1>
        <p className="text-lg text-neutral-600 mb-12">
          AI-powered recommendations to help you find products that actually work
        </p>

        {/* Step 1 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              1
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">Tell Us What You Need</h2>
              <p className="text-neutral-600">
                Describe your problem in plain language. "My kitchen counter is always cluttered" or
                "I need better cable management for my desk." Our AI understands what you're looking for
                and asks follow-up questions to find the best fit.
              </p>
            </div>
          </div>
        </div>

        {/* Step 2 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              2
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">AI Finds the Right Solutions</h2>
              <p className="text-neutral-600">
                Our AI analyzes your needs and recommends product types that solve your specific problem.
                Whether it's lazy susans for pantry organization or cable clips for your desk setup,
                we match you with solutions that work.
              </p>
            </div>
          </div>
        </div>

        {/* Step 3 */}
        <div className="bg-white rounded-2xl border-2 border-neutral-200 p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="bg-oak-600 text-white w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg flex-shrink-0">
              3
            </div>
            <div>
              <h2 className="text-xl font-bold text-neutral-900 mb-2">Browse Current Products</h2>
              <p className="text-neutral-600">
                See the most current products available on the market across different price points.
                We show you options from budget-friendly to premium so you can choose what fits
                your needs and budget.
              </p>
            </div>
          </div>
        </div>

        {/* Transparency Section */}
        <div className="bg-sage-50 rounded-2xl border border-sage-200 p-8 mt-12">
          <h2 className="text-xl font-bold text-neutral-900 mb-4">Transparency</h2>
          <p className="text-neutral-600 mb-4">
            Our recommendations are generated by AI to help you find products that solve real problems.
            We focus on matching you with the right solution, not pushing specific products.
          </p>
          <p className="text-neutral-600">
            <strong>Affiliate Disclosure:</strong> We earn commissions from purchases made through our links.
            This doesn't cost you extra and helps keep Prox free to use.
          </p>
        </div>

        <div className="mt-12 pt-8 border-t border-neutral-200 flex justify-between items-center">
          <a href="/" className="text-oak-600 hover:text-oak-700 font-medium">← Back to Home</a>
          <a href="/" className="bg-oak-600 hover:bg-oak-700 text-white px-6 py-3 rounded-lg font-medium transition-colors">
            Try It Now
          </a>
        </div>
      </div>
    </main>
  );
}
